### ISSUE TITLE
can you include tabs example

### ISSUE THREAD

**Issue by diomed** [mickasmt/astro-nomy#1]
hi 

very nice theme

could you possibly include tabs example somewhere
![2023-09-14 14 47 12 ui shadcn com 3c1e6cb07ad5](https://github.com/mickasmt/astro-nomy/assets/72777/6af27e51-9a82-4d2d-a975-2f599cd4a919)

**Comment by mickasmt** [comment]
Thanks you.
Sure! I'm on it.
