### ISSUE TITLE
how to handle navigation?

### ISSUE THREAD

**Issue by diomed** [mickasmt/astro-nomy#6]
I'd appreciate a bit of a guide for navigation.

I dont know how to create new pages in navigation, and would like to do so.
 For example, after I create `FAQ.astro` how to put it in navigation as new navigation menu item, just before About

**Comment by mickasmt** [comment]
Sure! 
I added links for menu navigation in the last commit. You can change this in `config/nav-menu`.
I use `mainNavItems` for to display the links in the sheet mobile.
