### ISSUE TITLE
A question from a beginner 🧐

### ISSUE THREAD

**Issue by CMAULTOP** [mickasmt/astro-nomy#8]
Why do I need to take the ui with react if then I have to export it to pages, but the point of astro is to optimize more, but because of the addition of react and non-optimizing UI parts, the meaning of using astro in general is lost, since then you can write it all on nextjs. And another question, astro seems to be more like for static, authorization is written in the plans, is it even possible?

**Comment by diomed** [comment]
astro is for static sites, yes. but it's main feature is that it can have dynamic islands in thosse static sites. 
so authorization is dynamic island here. 

basically it's up to you how much dynamic do you want it to be. 
main point of Astro would be to be static wherever it's not needed to be dynamic;
but when you need it, nothing stops you.
